### ISSUE TITLE
Failed to install.

### ISSUE THREAD

**Issue by hrqmonteiro** [shaunsingh/oxocarbon.nvim#1]
![Screenshot from 2022-07-30 22-31-05](https://user-images.githubusercontent.com/17055027/182005887-ef301fbb-c7f7-44b3-80f9-650fba731bad.png)

**Comment by shaunsingh** [comment]
Hi, what operating system are you using?

**Comment by yaikko** [comment]
There's a spelling mistake in the packer.nvim installation section of the readme.

use {'shaunsi**n**gh/oxocarbon.nvim', run = './install.sh'}

Missing the "n"

**Comment by shaunsingh** [comment]
Fixed, thanks!
