### ISSUE TITLE
panic when starting neovim

### ISSUE THREAD

**Issue by quyykk** [shaunsingh/oxocarbon.nvim#15]
I just updated oxocarbon using Packer and now I can't start neovim anymore:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("nocombine is not a boolean")', /<home>/.cargo/git/checkouts/nvim-oxi-68d2fdc1d1cdbe82/425e63d/nvim-oxi/src/lua/lua.rs:45:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
[1]    207427 IOT instruction (core dumped)  nvim
```

The backtrace (if enabled) is unreadable because it somehow corrupts my terminal and I can't type or scroll anymore. If you need the core dump I'll post it.

I'm using Neovim v0.7.2 on Arch.

**Comment by shaunsingh** [comment]
Should be fixed on master (actually this time)
