### ISSUE TITLE
oxothread panicked

### ISSUE THREAD

**Issue by quantum-booty** [shaunsingh/oxocarbon.nvim#16]
![image](https://user-images.githubusercontent.com/28958399/192108941-b2efe762-7f9a-4cd1-b576-198baa88e7ab.png)
Tested on latest neovim nightly.

**Comment by shaunsingh** [comment]
I think this should be fixed now, lmk if the issues persists

**Comment by xhxnna** [comment]
> I think this should be fixed now, lmk if the issues persists

Still crashing on my end with Neovim 0.8 stable.

**Comment by gegoune** [comment]
Also crashing on latest HEAD. Is it crashing for everyone or just subset of users (in which case some culprit could be found)?

**Comment by shaunsingh** [comment]
The odd thing is that it works for me so it may just be a subset of users. The stack trace gives an indication of an issue that might be handled within `nvim-oxi`, so I'll ask the author. For now everyone is also welcome to use the fennel branch (https://github.com/shaunsingh/oxocarbon.nvim/tree/fennel) version which doesn't require rust (lua based)

**Comment by DaftOdyssey** [comment]
Same exact issue as OP. Already had Rust installed for a while before the plug was installed so it must be something with nvim-oxi

**Comment by shaunsingh** [comment]
Oddly enough this doesn't happen on my main computer, but happens on my other install of neovim 0.8, probably something weird with nvim-oxi again. I'll update the dependences and poke around again to get it fixed, sorry for the delays!

**Comment by shaunsingh** [comment]
Fixed by https://github.com/shaunsingh/oxocarbon.nvim/pull/26, let me know if theres any other issues

**Comment by fitrh** [comment]
With `cargo build --release --features neovim-nightly` I'm getting this error

```sh
error[E0432]: unresolved import `std::ffi::c_int`
 --> /home/fitrh/.local/lib/rust/cargo/registry/src/github.com-1ecc6299db9ec823/luajit-bindings-0.2.0/src/error.rs:1:5
```
