### ISSUE TITLE
Failed to install packer

### ISSUE THREAD

**Issue by deniserdogan** [shaunsingh/oxocarbon.nvim#19]
``` :PackerInstall ``` fails when i try to install

![Screenshot 2022-09-30 at 23 51 43](https://user-images.githubusercontent.com/40524858/193354466-91ada4aa-dafb-4fc7-9db7-1ece760466b9.png)

**Comment by shaunsingh** [comment]
I assume this is because you don't have cargo/rust installed. Alternatively, you can give the fennel branch (https://github.com/shaunsingh/oxocarbon.nvim/tree/fennel) a start

**Comment by deniserdogan** [comment]
> I assume this is because you don't have cargo/rust installed. Alternatively, you can give the fennel branch (https://github.com/shaunsingh/oxocarbon.nvim/tree/fennel) a start

installing rust solved it thanks!
