### ISSUE TITLE
Crash on usage

### ISSUE THREAD

**Issue by micmine** [shaunsingh/oxocarbon.nvim#22]
I have been using your theme for the last view weeks. But lately I am not able to use it anymore.
When I enter the command:
``` txt
:colorscheme oxocarbon
```
Then neovim crashes with this message.
``` txt
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("\'ctermbg\' must be string or integer")', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/nvim-oxi-0.1.3/src/lua/lua.rs:42:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
fatal runtime error: Rust panics must be rethrown
fish: Job 1, 'nvim' terminated by signal SIGABRT (Abort)
```

**Comment by willfish** [comment]
I'm getting this, too. The event that stops it working for me is migrating from nvim 0.7 to nvim 0.8

**Comment by willfish** [comment]
There are newer versions of nvim-oxi available. I wonder if these have better compatibility with nvim 0.8

**Comment by shaunsingh** [comment]
Closing this in favor of https://github.com/shaunsingh/oxocarbon.nvim/issues/16
