### ISSUE TITLE
HDR Screenshots Look Terrible on Linux

### ISSUE THREAD

**Issue by wildwestrom** [shaunsingh/oxocarbon.nvim#24]
They're all way too low contrast. There's a stream of [theprimeagen](https://youtu.be/4lMiUAgkIAk?t=2440) spending way too long trying to find a good screenshot. (He finally manages to get one [here](https://youtu.be/4lMiUAgkIAk?t=2938).)

I don't know what the hell you used, but please for the love of your theme, don't disgrace it with these terrible screenshots. For the record, it looks great on my machine (and probably yours too).
![image](https://user-images.githubusercontent.com/77174844/195445866-42b72cbd-8bdf-405e-83c2-9be05eab5592.png)

**Comment by shaunsingh** [comment]
I believe the issue with the weird colors on prime's stream was largely due to his dark mode extension rather than the screenshot itself. Oddly enough this theme started off as a personal hack job of colors, I never imagined so many people would actually use it. That being said, the same applies to the screenshots, in the sense they just reflect whatever workflow I was working on at the time

I'm currently quite busy but If you'd be so kind as to take a few nice screenshots, I'd be happy to update the readme :)

**Comment by wildwestrom** [comment]
> I believe the issue with the weird colors on prime's stream was largely due to his dark mode extension rather than the screenshot itself.

Nuh uh. Here's your screenshots on the left, mine on the right. PNGs don't lie.
![20221014_01h30m03s_grim](https://user-images.githubusercontent.com/77174844/195769598-8ace972a-3545-4033-83d4-797c1a03289f.png)

Here's a bunch you can use though:
![2022-10-14T01:22:10,750078961-04:00](https://user-images.githubusercontent.com/77174844/195769668-eab9386e-18da-4bf2-8439-18fd5b709bc1.png)
![2022-10-14T01:19:08,677997188-04:00](https://user-images.githubusercontent.com/77174844/195769670-eeae3cc7-2e8c-49c2-baf9-531b8b928458.png)
![2022-10-14T01:15:14,763800819-04:00](https://user-images.githubusercontent.com/77174844/195769672-0b6c8e23-d033-4b74-b3aa-7a9036d069c8.png)
![2022-10-14T01:14:03,971522334-04:00](https://user-images.githubusercontent.com/77174844/195769673-05cbe2ba-f5a7-46b7-856a-149e03d41f46.png)
![2022-10-14T01:13:16,463333715-04:00](https://user-images.githubusercontent.com/77174844/195769676-6dce9e07-66a5-46b6-8975-7b9d442c6cf2.png)
![2022-10-14T01:12:32,037179346-04:00](https://user-images.githubusercontent.com/77174844/195769677-4ae15820-a204-4355-a2eb-f3bc70b96b60.png)
![2022-10-14T01:11:20,258736124-04:00](https://user-images.githubusercontent.com/77174844/195769678-20ebc158-12d0-4b85-9c28-ea20447f2747.png)
![2022-10-14T01:09:26,468274114-04:00](https://user-images.githubusercontent.com/77174844/195769679-50c8a78f-5198-41c4-bdb9-5f10ae274e6f.png)

**Comment by shaunsingh** [comment]
> Nuh uh. Here's your screenshots on the left, mine on the right. PNGs don't lie.

Seems like the issue is the screenshot I made in the README is encoded with HDR, and the hdr->sdr conversion sucks on linux (and it's pretty spot on in macOS).

**Comment by wildwestrom** [comment]
> Seems like the issue is the screenshot I made in the README is encoded with HDR, and the hdr->sdr conversion sucks on linux (and it's pretty spot on in macOS).

Ah, well that explains it, so it's not your screenshots that suck, it's my OS that sucks (in this case anyway). I guess then theoretically I could do HDR->SDR on your original screenshots with GIMP or something.

**Comment by wildwestrom** [comment]
Here, I used different ICC rendering intent profiles to convert your screenshot with GIMP.

<details>
  <summary>Original</summary>
  
  ![oxocarbon-dark](https://user-images.githubusercontent.com/77174844/195908407-773c969f-b0d8-4e98-b25d-afa5d42611a1.png)
  
</details>

<details>
  <summary>Absolute Colorimetric</summary>

![oxocarbon-dark-absolute-colorimetric](https://user-images.githubusercontent.com/77174844/195908513-91d961d5-f858-4ced-a142-a809e3fbc56f.png)
  
</details>

<details>
  <summary>Perceptual</summary>
  
![oxocarbon-dark-perceptual](https://user-images.githubusercontent.com/77174844/195908556-85912304-a977-454a-883b-e3dda9fb0e5b.png)

</details>

<details>
  <summary>Relative Colorimetric</summary>

![oxocarbon-dark-relative-colorimetric](https://user-images.githubusercontent.com/77174844/195908592-7cab84a7-69b1-4159-bc92-0b4d2cb7d1cf.png)

</details>

<details>
  <summary>Saturation</summary>

![oxocarbon-dark-saturation](https://user-images.githubusercontent.com/77174844/195908606-17eaeeab-a470-4a30-a86a-927894886088.png)

</details>

**Comment by shaunsingh** [comment]
I updated a few aspects of the theme and pushed a new screenshot to the readme showcasing everything. It should render just fine on linux now
