### ISSUE TITLE
Inconsistent colors

### ISSUE THREAD

**Issue by sorashi** [shaunsingh/oxocarbon.nvim#29]
I have treesitter with typescript and tsx installed.

When I do this:

```lua
vim.cmd.colorscheme "oxocarbon"
```

I get incorrect colors:

![Screenshot from 2022-10-23 14-31-58](https://user-images.githubusercontent.com/6270283/197393067-f851b41e-05f9-4551-b8f9-0ee7bfc271b4.png)

---

But when I load a different theme first:

```lua
vim.cmd.colorscheme "everforest"
vim.cmd.colorscheme "oxocarbon"
```

I get correct colors:

![Screenshot from 2022-10-23 14-41-13](https://user-images.githubusercontent.com/6270283/197393087-2be6c3ac-dca2-427d-9d23-b1b6fdda8a31.png)

Am I doing something wrong? It might have to do something with #4

**Comment by sorashi** [comment]
Might be caused by this: https://github.com/shaunsingh/oxocarbon.nvim/issues/31#issuecomment-1296077835

Treesitter changed it's highlight groups in this commit https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f

Everforest is already fixed https://github.com/sainnhe/everforest/commit/c60a594cc4adbfb863d3186f730765b0e1cb85eb

**Comment by shaunsingh** [comment]
Added support for new tree-sitter highlights, sorry for the delay

**Comment by sorashi** [comment]
Thank you! No worries about any delays, this is free software after all. :smiley:
