### ISSUE TITLE
The colors have nothing to do with your screenshot, why?

### ISSUE THREAD

**Issue by hrqmonteiro** [shaunsingh/oxocarbon.nvim#31]
![Screen Shot 2022-10-28 at 20 26 58](https://user-images.githubusercontent.com/17055027/198752058-773a2690-cb09-421b-9b06-d2dd1b21bc13.png)
![Screen Shot 2022-10-28 at 20 27 02](https://user-images.githubusercontent.com/17055027/198752061-8213a3a5-87f7-4d2b-b515-9c24c92c9538.png)

I have treesitter and the treesiter-textobjects configured exactly as yours..

**Comment by dzecs** [comment]
Had the same issue, apparently treesitter made some breaking changes, check https://www.reddit.com/r/neovim/comments/y5rofg/recent_treesitter_update_borked_highlighting/

This fix worked for me
https://gist.github.com/jdrouhard/dccbb692e901d5e0a00a3a4c126079c6

**Comment by shaunsingh** [comment]
I added support for the new tree-sitter highlights. The base colors of the theme and syntax mapping have changed *slightly* to align better with the official ibm carbon, but I've also updated the screenshots accordingly

**Comment by Herz3h** [comment]
I have same issue in kitty + nvim 0.9.4 I even removed nvim-treesitter plugin:

See this simple rust file:
<img width="148" alt="image" src="https://github.com/nyoom-engineering/oxocarbon.nvim/assets/1900696/a01f38dd-5141-4071-aed0-a5962c1df7bb">
