### ISSUE TITLE
Abort --> free-ing un-malloc'd memory - when starting on MacOS / iterm2

### ISSUE THREAD

**Issue by rrichardson** [shaunsingh/oxocarbon.nvim#33]
I'm running nvim version 0.9.0 installed from Brew 

After setting the color theme to oxocarbon,  neovim crashes with this message:

```
nvim(64121,0x1047ec580) malloc: *** error for object 0x1046886ae: pointer being freed was not allocated
nvim(64121,0x1047ec580) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort
nvim init.lua
```

I'm assuming that this is due to the new nvim minor version.  Just guessing that the native oxocarbon stuff was compiled against 0.8.*. 

## Other details

oxocarbon version:  commit: bb59d8689820a0b5f1cf9508ebc0d429b15348d1

neovim version:

```
❯ nvim --version
NVIM v0.9.0-dev-1549+g523b1943c-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ririchardson@LUSHF66P5Q2K0

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-523b194/share/nvim"

Run :checkhealth for more info
```

**Comment by shaunsingh** [comment]
Yup, looks like I need to just update the `nvim-oxi` dependency to build against the 0.8.1 api. I'll do it shortly
