### ISSUE TITLE
It doesn't tell you when it fails to install due to Rust not being installed

### ISSUE THREAD

**Issue by creemy0cheesekake** [shaunsingh/oxocarbon.nvim#6]
I used Vim-Plug and got an error after downloading that said `Post-update hook for oxocarbon.nvim ... Exit status: 127`

After some digging, I realized that I must have uninstalled rust at some point because it said cargo wasn't installed, but this isn't clear from the error message.

I'm not sure if this is even fixable, because it seems to just be how Vim-Plug displays the errors by only giving the exit status, but I just wanted to let you know

**Comment by head-gardener** [comment]
Well, I think the README is pretty clear about this. What it's not clear about, however, is that the Cargo has to be no older than 2021, which can bite you in the ass with Debian if you rely on apt.

**Comment by shaunsingh** [comment]
No longer uses rust :)
