### ISSUE TITLE
[centos 7] Issue with Vim-plug, the theme doesn't work

### ISSUE THREAD

**Issue by Peskoo** [shaunsingh/oxocarbon.nvim#7]
Hello,

Maybe I've done something wrong, idk.  
1. I installed rust with `rustc 1.62.1 (e092d0b6b 2022-07-16)`, (start new session to reload zsh)
2. then I add this line `Plug 'shaunsingh/oxocarbon.nvim', { 'do': './install.sh' }` to add the theme with vimplug.
3. Added this line too `colorscheme oxocarbon`
4. Install plug ; everything is ok on screen
5. But nothing is happening. No theme loaded.

I tried to start `./install.sh` and I have this error:
<img width="670" alt="Capture d’écran 2022-08-05 à 12 28 24" src="https://user-images.githubusercontent.com/13115709/183058883-cff40177-0082-4712-bd8e-de5f389574ff.png">
The pictures shows that « target/release/liboxocarbon.so » and « lua/oxocarbon.so » targeted the same file

I'm not sure what to do next ? Or if I did something wrong during the first steps

Thanks for your help :)
have a nice day

**Comment by zhufenggood** [comment]
Go to directory `~/.local/share/nvim/plugged/oxocarbon.nvim`.
Manually delete file  `rm lua/oxocarbon.so`.
Run `./install.sh` to generate file again.
Reopen terminal or neovim gui. Now, it's work.
